branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# CØSMOS Faucet"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files: [version]
          from: ^.+$
          to: ${nextRelease.version}
          countMatches: true
          results:
            - file: version
              hasChanged: true
              numMatches: 1
              numReplacements: 1
        - files: [.github/package.json]
          from: '"version": "\d\.\d\.\d",'
          to: '"version": "${nextRelease.version}",'
          countMatches: true
          results:
            - file: .github/package.json
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/exec"
    - prepareCmd: |
        make build-go-all
  - - "@semantic-release/github"
    - assets:
        - name: cosmos-faucet_darwin_amd64
          label: Binary - Darwin amd64
          path: "./target/dist/darwin/amd64/cosmos-faucet"
        - name: cosmos-faucet_darwin_arm64
          label: Binary - Darwin arm64
          path: "./target/dist/darwin/arm64/cosmos-faucet"
        - name: cosmos-faucet_linux_amd64
          label: Binary - Linux amd64
          path: "./target/dist/linux/amd64/cosmos-faucet"
        - name: cosmos-faucet_windows_amd64.exe
          label: Binary - Windows amd64
          path: "./target/dist/windows/amd64/cosmos-faucet.exe"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - version
        - .github/package.json
      message: "chore(release): perform release ${nextRelease.version}"
