name: Build

on:
  workflow_call:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build-go:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: "1.18.1"

      - name: Build go project
        run: |
          make build

  build-docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build .
