name: Check

on:
  workflow_call:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-schema:
    runs-on: ubuntu-20.04
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check graphql schema changes
        uses: kamilkisiela/graphql-inspector@v3.1.2
        with:
          schema: 'main:graph/schema.graphqls'
